modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/fncct/issues"

[[mods]]
modId="fncct"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/wolfieboy09/FNCCT/refs/heads/master/versions.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.fncct]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.fncct]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.fncct]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.101.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fncct]]
    modId="fluxnetworks"
    mandatory=true
    versionRange="[7.0.9.15,)"
    ordering="NONE"
    side="BOTH"
